Configure building Rust project for Raspberry Pi
UCI-HyperXite/hx9-control-system pull request #20
Opened 2024-02-15 23:06 UTC by taesungh

Resolves #1.

## Changes
- Add Cargo config to set build target platform and linker
- Include setup instructions in README

## Testing
1. Build the project with the ARM target from your personal machine
2. Attempt to run the executable on the Raspberry Pi in lab
3. Observe the program behaves as expected

## Remaining tasks
- [x] Include compiler installation instructions for macOS
- [x] Include compiler installation instructions for Windows
- [x] Include alternative instructions for using [cross](https://github.com/cross-rs/cross)
- [x] Update checks workflow to support cross-compilation

2024-02-24 00:34 UTC, taesungh commented
Following from #15, we'll also need to update the checks workflow to be able to compile for arm-linux.

2024-02-26 20:14 UTC, SM-dot reviewed
Thanks for setting this up! 

- Is there a certain minimum required versions of Rust, cargo-watch, and Docker required?

- While the cross-compilation section is thorough for Windows/Linux, the instructions for MacOS appear relatively brief. Would it be possible to  provide additional details or addressing specific MacOS nuances to maintain consistency and completeness across all platforms?

2024-02-26 23:26 UTC, taesungh commented
We specify Rust edition 2021 in `Cargo.toml`. We would expect developers to use modern versions of cargo and rustc although older versions _should_ also work. The Docker setup instructions actually apply to all host operating systems, and Sam will be providing a separate section for native compilation on Windows. There aren't many nuances with using the ARM compiler on macOS although we may need a separate script to distinguish host OS (pending discussion with Sam).

2024-02-26 23:47 UTC, SM-dot approved these changes

2024-02-29 04:42 UTC, SM-dot approved these changes

2024-03-01 18:47 UTC, samderanova requested changes
Looks good, one small issue.

2024-03-01 18:47 UTC, samderanova commented on pod-operation/README.md
> +for Windows or Linux.
A bit repetitive here, since we already state this in the sentence before.

2024-03-01 20:04 UTC, samderanova approved these changes
Thanks for working on this!

2024-03-01 22:36 UTC, merged