Display current FSM state in control panel
UCI-HyperXite/hx9-control-system pull request #61
Opened 2024-05-18 22:20 UTC by samderanova

Resolves #50.

- Created a new enum `State` that represents the current state of the pod in the GUI frontend
- Modify `PodData` interface to include the current state as a field
- Display the current state in `ControlPanel`

2024-05-25 18:23 UTC, taesungh requested changes
Thanks for working on this, one issue on usage and thoughts on initial value along with smaller chore.

2024-05-25 18:23 UTC, taesungh commented on control-station/src/services/PodSocketClient.ts
> +		this.setPodData((d) => ({ ...d, state: State.Load }));
Issue [repeating]: the control station must not falsely claim the pod state was updated when it actually might not have been. We'll need to update `podData` only when a proper acknowledgement is received (within the callback).

2024-05-27 05:05 UTC, taesungh approved these changes
Looks alright for now, thanks for also adding the `Faulted` state. Might want to eventually consider using SASS or CSS modules for more organized styles.

2024-05-28 03:47 UTC, ryescholin approved these changes
Looks great!

2024-05-28 04:09 UTC, merged