Display sensor values in control station GUI
UCI-HyperXite/hx9-control-system pull request #81
Opened 2024-05-27 09:16 UTC by ryescholin

Emit sensor values in `pod_periodic` (might move some to `running_periodic`) and display values in sensor boxes in GUI.
Resolves #44.

2024-05-31 23:53 UTC, samderanova commented on control-station/src/services/usePodData.tsx
>  		connected: false,
I think we can remove this line because the state will already tell us whether the GUI is connected to the pod or not.

2024-06-01 00:01 UTC, taesungh requested changes
Thanks for working on this. To keep the PR focused on a specific issue, please refrain from mixing changes that are out of scope. Some small issues and some minor suggestions.

2024-06-01 01:39 UTC, vrushang1234 commented on control-station/src/components/SensorBoxes/Sensors/SensorsContainer.tsx
> +			<SensorBox title="Speed" value={podData.gyroscope} />
These values are just place holders and I will be changing them in the future as per the requirements

2024-06-01 01:41 UTC, vrushang1234 commented on control-station/src/services/PodSocketClient.ts
> +	gyroscope: number;
Again, these are just placeholders and I will be changing them. My goal for this PR was just to send some data GUI and show it

2024-06-01 01:41 UTC, vrushang1234 commented on control-station/src/views/Dashboard/Dashboard.tsx
> -			<StatusIndicator />
I did this to make more space for other sensorboxes.

2024-06-01 02:20 UTC, taesungh commented on control-station/src/services/PodSocketClient.ts
>  interface Wheel_Encoder {
Chore: interface name should be PascalCase

2024-06-01 03:21 UTC, taesungh commented on control-station/src/services/PodSocketClient.ts
> +	serverResponse: (data: PodData) => void;
Chore: Not sure why TypeScript didn't catch this, but we'll also need this to be `Partial`

2024-06-01 03:34 UTC, samderanova approved these changes

2024-06-01 03:39 UTC, taesungh approved these changes
Approving to unblock additional work on GUI, please make sure to **squash** during merge.

2024-06-01 03:41 UTC, merged